src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=CarRepository::class)
 * @Vich\Uploadable
 */
class Car
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $brand;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $model;

    /**
     * @ORM\Column(type="integer")
     */
    private $horsepower;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $engine;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $color;

    /**
     * @ORM\ManyToOne(targetEntity=Company::class, inversedBy="cars")
     * @ORM\JoinColumn(nullable=false)
     */
    private $company;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="car")
     */
    private $reservations;

    /**
     * @ORM\Column(type="text", length=16383, nullable=true)
     */
    private $description;

    /**
     * @Vich\UploadableField(mapping="car_image", fileNameProperty="image")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=511, nullable=true)
     * @var string|null
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     * @var DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="date")
     */
    private $year;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->updatedAt = new DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->getBrand() . ' ' . $this->getModel();
    }

    public function getHorsepower(): ?int
    {
        return $this->horsepower;
    }

    public function setHorsepower(int $horsepower): self
    {
        $this->horsepower = $horsepower;

        return $this;
    }

    public function getEngine(): ?string
    {
        return $this->engine;
    }

    public function getHasImage(): bool
    {
        return !empty($this->image);
    }

    public function setEngine(string $engine): self
    {
        $this->engine = $engine;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setCar($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getCar() === $this) {
                $reservation->setCar(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if ($imageFile) {
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getYear()
    {
        return $this->year ? $this->year->format('Y') : 0;
    }

    public function setYear(string $year): self
    {
        $this->year = new DateTime($year.'-01-01');

        return $this;
    }
}

templates/admin.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ t('admin.title')|trans }}{% endblock %}
{% block main %}
    {{ render(controller('App\\Controller\\AdminMenuController:menu')) }}
    {% block adminContent %}
        <div class="container container--admin">
            <section class="section">
                <h1>{{ t('admin.title')|trans }}</h1>
                <div class="stats">
                    {% for stat in stats %}
                        <div class="stats__stat">
                            <div class="stats__number">{{ stat.number }}</div>
                            <div class="stats__title">{{ t(stat.title)|trans }}</div>
                        </div>
                    {% endfor %}
                </div>
            </section>
        </div>
    {% endblock %}
{% endblock %}

templates/adminCar.html.twig
{% extends "admin.html.twig" %}

{% block adminContent %}
    <div class="container container--admin">
        <section class="section">
            <h1>{{ t('admin.cars.titles.edit')|trans }}</h1>
            {{ form(form, {'attr': {'class': 'adminForm'}}) }}
        </section>
    </div>
{% endblock %}

templates/adminCars.html.twig
{% extends "admin.html.twig" %}

{% block adminContent %}
    <div class="container container--admin">
        <section class="section">
            <h1>{{ t('admin.cars.titles.list')|trans }}</h1>
            {% include 'pagination.html.twig' with {'base_link': (path('app_admin_cars') ~ '?order=' ~ current_order ~ '&direction=' ~ current_direction ~ '&per_page=' ~ per_page)} %}
            {% include 'sortableList.html.twig' with {'translation_base' : 'admin.cars.list', 'data': cars, 'location': 'app_admin_cars', 'edit_location': 'app_admin_car', 'edit': true} %}
            {% include 'pagination.html.twig' with {'base_link': (path('app_admin_cars') ~ '?order=' ~ current_order ~ '&direction=' ~ current_direction ~ '&per_page=' ~ per_page), 'variant': 'top'} %}
        </section>
    </div>
{% endblock %}

templates/adminReservations.html.twig
{% extends "admin.html.twig" %}

{% block adminContent %}
    <div class="container container--admin">
        <section class="section">
            <h1>{{ t('admin.reservations.title')|trans }}</h1>
            {% include 'pagination.html.twig' with {'base_link': (path('app_admin_reservations') ~ '?order=' ~ current_order ~ '&direction=' ~ current_direction ~ '&per_page=' ~ per_page) } %}
            {% include 'sortableList.html.twig' with {'translation_base' : 'reservations.list', 'data': reservations, 'location': 'app_admin_reservations', 'edit': false} %}
            {% include 'pagination.html.twig' with {'base_link': (path('app_admin_reservations') ~ '?order=' ~ current_order ~ '&direction=' ~ current_direction ~ '&per_page=' ~ per_page), 'variant': 'top'} %}
        </section>
    </div>
{% endblock %}

templates/adminUser.html.twig
{% extends "admin.html.twig" %}

{% block adminContent %}
    <div class="container container--admin">
        <section class="section">
            <h1>{{ t('admin.users.titles.edit')|trans }}</h1>
            {{ form(form, {'attr': {'class': 'adminForm'}}) }}
        </section>
    </div>
{% endblock %}

templates/adminUsers.html.twig
{% extends "admin.html.twig" %}

{% block adminContent %}
    <div class="container container--admin">
        <section class="section">
            <h1>{{ t('admin.users.titles.list')|trans }}</h1>
            {% include 'pagination.html.twig' with {'base_link': (path('app_admin_users') ~ '?order=' ~ current_order ~ '&direction=' ~ current_direction ~ '&per_page=' ~ per_page)} %}
            {% include 'sortableList.html.twig' with {'translation_base' : 'admin.users.list', 'data': users, 'location': 'app_admin_users', 'edit_location': 'app_admin_user', 'edit': true} %}
            {% include 'pagination.html.twig' with {'base_link': (path('app_admin_users') ~ '?order=' ~ current_order ~ '&direction=' ~ current_direction ~ '&per_page=' ~ per_page), 'variant': 'top'} %}
        </section>
    </div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html lang="pl-PL">
    {{ include('head.html.twig') }}
    <body>
        {{ include('flash.html.twig') }}
        <header>
            {% block menu %}
                {{ render(controller('App\\Controller\\MenuController:menu')) }}
            {% endblock %}
        </header>
        <main>            
            {% block main %}
                <div class="home container">
                    <div class="title">
                        <h1 class="title__text">{{ t('home.header')|trans }}</h1>
                        <img src="{{asset('build/images/giulia.png')}}" title="giulia" alt="giulia" class="title__image">
                    </div>

                    <div class="container">
                        <section class="section section--centered">
                            <h2 class="home__header">{{ t('home.aboutUs')|trans }}</h2>
                            <div class="home__text">{{ t('home.about')|trans }}</div>
                            <a class="button button--callToAction home__button" href="{{ path('app_register') }}">{{ t('home.tryNow')|trans }}</a>
                        </section>

                        <section class="section section--centered">
                            <h2 class="home__header">{{ t('home.promo')|trans }}</h2>
                            <div class="promo">
                                {% for element in promo %}
                                    <div class="promo__element promo__element--{{ element.type }}">
                                        <div class="promo__title">{{ t(element.title)|trans }}</div>
                                        <img src="{{ asset(element.asset) }}" alt="{{ t(element.title)|trans }}" class="promo__image">
                                    </div>
                                {% endfor %}
                            </div>
                        </section>

                        <section class="section">
                            <h2 class="home__header">{{ t('home.prices')|trans }}</h2>
                            <div class="services">
                                {% for service in services %}
                                    <div class="services__service">
                                        <h3 class="services__title">{{ t(service.title)|trans }}</h3>
                                        <ul class="services__list">
                                            {% for element in service.list %}
                                                <li class="services__element"><span class="services__icon">{% if element.enabled|default %}✔️{% else %}❌{% endif %}</span> {{ t(element.title)|trans }}</li>
                                            {% endfor %}
                                        </ul>
                                        <h4 class="services__price">{{ t(service.price)|trans }}</h4>
                                        <div class="services__buttonContainer">
                                            {% if service.button.enabled|default %}
                                                <a class="services__button button button--{{ service.button.type }}" href="{{ path('app_register') }}">{{ t(service.button.text)|trans }}</a>
                                            {% else %}
                                                <div class="services__button button button--{{ service.button.type }}">{{ t(service.button.text)|trans }}</div>
                                            {% endif %}
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </section>
                    </div>
                </div>
            {% endblock %}
        </main>
        {% block footer %}
            <footer class="footer">{{ t('footer.authors')|trans|raw }}</footer>
        {% endblock %}
    </body>
</html>

templates/flash.html.twig
{% block flash %}
    <div class="flashes">
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="flashes__flash flashes__flash--{{ label }}">
                    <button type="button" class="flashes__close_button">X</button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}
    </div>
{% endblock %}

templates/head.html.twig
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{ asset('build/images/favicon.ico') }}" >
    <title>{% block title %}{{ t('home.welcome')|trans }}{% endblock %}</title>
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>

templates/menu.html.twig
<nav class="navbar">
    <button type="button" class="menuHamburgerButton HamburgerHandler" data-autohide="true"><span class="menuHamburgerButtonInside"></span></button>
    <ul class="menu">
        {% for menu_item in menu %}
            <li class="menuItem">
                <a class="button button--{{ menu_item.type }}" href="{{ path(menu_item.location) }}" title="{{ menu_item.title }}">
                    {{ menu_item.title }}
                </a>
            </li>
        {% endfor %}
    </ul>
</nav>

templates/pagination.html.twig
{% block pagination %}
    <div class="pagination">
        <select name="per_page" class="per_page stylizedSelect" data-variant="{% if variant|default %}{{ variant }}{% else %}bottom{% endif %}">
            {% for option in [1, 5, 10, 25, 50, 100, 250] %}
                <option {% if per_page == option %}selected{% endif %} value="{{ option }}">{{ option }}</option>
            {% endfor %}
        </select>
        {% if pages > 1 %}
                <div class="pages">
                    {% if page > 2 %}
                        <a tabindex="0" href="{{ base_link ~ '&page=' ~ 1 }}" class="page_link page_link--end">1</a>
                    {% endif %}
                    {% if page > 3 %}
                        <div class="page_link page_link--separator">...</div>
                    {% endif %}
                    {% for i_page in range(max(1, page - 1), min(page + 1, pages)) %}
                        <a tabindex="0" href="{{ base_link ~ '&page=' ~ i_page }}" class="page_link {% if i_page == page %}page_link--current{% endif %}">{{ i_page }}</a>
                    {% endfor %}
                    {% if page < pages - 2 %}
                        <div class="page_link page_link--separator">...</div>
                    {% endif %}
                    {% if page < pages - 1 %}
                        <a tabindex="0" href="{{ base_link ~ '&page=' ~ pages }}" class="page_link page_link--end">{{ pages }}</a>
                    {% endif %}
                </div>
        {% endif %}
    </div>
{% endblock %}

templates/reserve.html.twig
{% extends "base.html.twig" %}

{% block main %}
    <div class="container container--admin reserve">
        <section class="section">
            <h1>{{ t('reservation.title')|trans }}</h1>
            {{ form(form, {'attr': {'class': 'adminForm reserveForm'}}) }}
        </section>
        {% if formValid %}
            <section class="section">
                <h2>
                    {% if cars|length > 0 %}
                        {{ t('reservation.found')|trans ~ ' ' ~  cars|length}}
                    {% else %}
                        {{ t('reservation.carsAmount.zero')|trans }}
                    {% endif %}
                </h2>
                <div class="cars">
                    {% for car in cars %}
                        <div class="cars__car">
                            <div class="cars__title">{{ car.brand}} {{ car.model }}</div>
                            <div class="cars__information">
                                {% if car.hasImage|default %}
                                    <img src="{{ vich_uploader_asset(car) }}" alt="{{ car.brand }} {{ car.model }}" class="cars__image">
                                {% endif %}
                                <div class="cars__informationContainer">
                                    <div class="cars__info"><span class="cars__label">{{ t('reservation.cars.horsepower')|trans }}: </span>{{ car.horsepower }}</div>
                                    <div class="cars__info"><span class="cars__label">{{ t('reservation.cars.engine')|trans }}: </span>{{ car.engine }}</div>
                                    <div class="cars__info"><span class="cars__label">{{ t('reservation.cars.color')|trans }}: </span>{{ car.color }}</div>
                                    <div class="cars__info"><span class="cars__label">{{ t('reservation.cars.year')|trans }}: </span>{{ car.year }}</div>
                                </div>
                            </div>
                            <div class="cars__description">{{ car.description}}</div>
                            <a class="cars__button" href="{{ path('app_reserve_id', {'id': car.id, 'start': start, 'end': end}) }}">{{ t('reservation.reserve')|trans }}</a>
                        </div>
                    {% endfor %}
                </div>
            </section>
        {% endif %}
    </div>
{% endblock %}

templates/sortableList.html.twig
<div class="sortable_list">
    <div class="sortable_list__sorts">
        <select class="stylizedSelect sortable_list__sort sortable_list__sort--property">
            {% for field in fields %}
                {% if field.sortable %}
                    <option {% if field.sort|default %} value="{{ field.sort }}" {% if field.sort == current_order %}selected{% endif %} {% else %} value="{{ field.name }}" {% if field.name == current_order %}selected{% endif %} {% endif %}>{{ t( translation_base ~ '.' ~ field.name)|trans }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <select class="stylizedSelect sortable_list__sort sortable_list__sort--direction">
            <option value="ASC" {% if 'ASC' == current_direction %}selected{% endif %}>{{ t("sortableList.asc")|trans }}</option>
            <option value="DESC" {% if 'DESC' == current_direction %}selected{% endif %}>{{ t("sortableList.desc")|trans }}</option>
        </select>
    </div>
    <div class="sortable_list__table">
        <div class="sortable_list__row sortable_list__row--header">
            {% for field in fields %}
                <div class="sortable_list__field sortable_list__field--header" style="width: {{ field.width }};">
                    <span>{{ t( translation_base ~ '.' ~ field.name)|trans }}</span>
                    {% if field.sortable %}
                        <div class="sortable_list__sort_buttons">
                            <a tabindex="0" class="sortable_list__sort_button{% if (((field.name == current_order) or ((field.sort|default) and (field.sort == current_order))) and ('ASC'  == current_direction))  %} sortable_list__sort_button--active {% endif %}" title="{{ t('sortableList.orderBy')|trans }} {{ t( translation_base ~ '.' ~ field.name)|trans }} {{ t('sortableList.asc')|trans }}" href="{{ path(location)}}?order={% if field.sort|default %}{{ field.sort }}{% else %}{{ field.name }}{% endif %}&direction=ASC&per_page={{ per_page }}">^</a>
                            <a tabindex="0" class="sortable_list__sort_button{% if (((field.name == current_order) or ((field.sort|default) and (field.sort == current_order))) and ('DESC' == current_direction))  %} sortable_list__sort_button--active {% endif %}" title="{{ t('sortableList.orderBy')|trans }} {{ t( translation_base ~ '.' ~ field.name)|trans }} {{ t('sortableList.desc')|trans }}" href="{{ path(location)}}?order={% if field.sort|default %}{{ field.sort }}{% else %}{{ field.name }}{% endif %}&direction=DESC&per_page={{ per_page }}">^</a>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        {% for object in data %}
            <div class="sortable_list__row" data-id="{{object.id}}">
                {% for field in fields %}
                    {% if field.name == 'action' %}
                        <div class="sortable_list__field sortable_list__field--edit" data-label="{{ t( translation_base ~ '.' ~ field.name)|trans }}" style="width: 10%;">
                            <div class="sortable_list__admin_list_buttons">
                                {% if edit|default %}
                                    <a href="{{ path(edit_location, {'id': object.id}) }}" title="{{ t("sortableList.edit")|trans }}" class="sortable_list__admin_list_button sortable_list__admin_list_button--edit Edit icon icon-edit"></a>
                                {% endif %}
                                <button title="{{ t("sortableList.delete")|trans }}" class="sortable_list__admin_list_button sortable_list__admin_list_button--delete Delete icon icon-delete" data-location="{{ path( location ~ '_delete', {'id': object.id}) }}"></button>
                            </div>
                        </div>
                    {% elseif field.name == 'image' %}
                        <div class="sortable_list__field" data-label="{{ t( translation_base ~ '.' ~ field.name)|trans }}" style="width: {{ field.width }};">
                            <a href="{{ object.image }}" download><img src="{{ object.image }}" alt=""></a>
                        </div>
                    {% else %}
                        <div class="sortable_list__field" data-label="{{ t( translation_base ~ '.' ~ field.name)|trans }}" style="width: {{ field.width }};">{{ (attribute(object, field.name)|striptags)|replace({'_': '_<wbr>', '@': '@<wbr>'})|raw }}</div>
                    {% endif %}
                {% endfor %}

            </div>
        {% endfor %}
    </div>
</div>

templates/userReservations.html.twig
{% extends "user.html.twig" %}

{% block userContent %}
    <div class="container container--admin">
        <section class="section">
            <h1>{{ t('user.reservations.title')|trans }}</h1>
            {% include 'pagination.html.twig' with {'base_link': (path('app_user_reservations') ~ '?order=' ~ current_order ~ '&direction=' ~ current_direction ~ '&per_page=' ~ per_page) } %}
            {% include 'sortableList.html.twig' with {'translation_base' : 'reservations.list', 'data': reservations, 'location': 'app_user_reservations', 'edit': false} %}
            {% include 'pagination.html.twig' with {'base_link': (path('app_user_reservations') ~ '?order=' ~ current_order ~ '&direction=' ~ current_direction ~ '&per_page=' ~ per_page), 'variant': 'top'} %}
        </section>
    </div>
{% endblock %}